<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>app_escritorio</RootNamespace>
    <!-- Avisos de nulabilidad desactivados: el código no usa anotaciones de tipos que aceptan null -->
    <NoWarn>CS8618;CS8602;CS8604;CS8600;CS8625</NoWarn>
  </PropertyGroup>

</Project>